[REG-1317] Updates for GetState protected change
Regression-Games/RGUnitySample pull request #10
Opened 2023-10-23 14:36 UTC by RG-nAmKcAz

2023-10-23 20:42 UTC, abeizer approved these changes

2023-10-23 21:04 UTC, vontell approved these changes

2023-10-23 21:20 UTC, rcornwall-reg approved these changes

2023-10-23 21:21 UTC, rcornwall-reg requested changes
Seeing the error:

```Assets/RGScripts/RGStates/Player_RGState.cs(22,55): error CS0507: 'Player_RGState.GetState()': cannot change access modifiers when overriding 'public' inherited member 'RGState.GetState()'```

I believe it also needs to change the modifier in `RGState.cs`

2023-10-24 12:36 UTC, RG-nAmKcAz commented
@rcornwall-reg your request for changes is because this repo points to 'main' for the SDK and the SDK changes aren't merged yet

2023-10-24 16:06 UTC, rcornwall-reg approved these changes

2023-10-25 15:48 UTC, addisonbgross approved these changes

2023-10-25 19:02 UTC, merged