[REG-1099] GitHub Action Support / Example
Regression-Games/RGUnitySample pull request #6
Opened 2023-08-22 15:45 UTC by vontell

This PR serves as an example for CI/CD support for Regression Games in GitHub Actions.

Because of the way this pipeline was setup, some of the code is actually already in main.

2023-08-29 14:38 UTC, RG-nAmKcAz requested changes
What are the new `InitTestScene#####` files for ?

Are these intentional, or something that should be in .gitignore ?

2023-08-29 14:38 UTC, RG-nAmKcAz commented on Assets/Tests/RGBotTests.cs
> +        int defaultBotId = 109;
this value seems arbitrary or specific to 1 developer's specific environment

2023-09-07 14:06 UTC, RG-nAmKcAz approved these changes

2023-09-07 14:06 UTC, RG-nAmKcAz requested changes
Marking request changes so that we don't accidentally merge without updating the branch after merging PR (https://github.com/Regression-Games/RGUnityBots/pull/31)

2023-09-07 14:07 UTC, RG-nAmKcAz commented
@abeizer you can mark this approved, Have confirmed this is now working 

(Test Result: https://github.com/Regression-Games/RGUnitySample/actions/runs/6110621216)

2023-09-07 16:01 UTC, RG-nAmKcAz approved these changes
@vontell Version is now updated... Approved assuming the pipeline passes 
Looks like you'll still need @abeizer to approve though

2023-09-07 16:03 UTC, abeizer approved these changes

2023-09-07 16:17 UTC, vontell commented
@RG-nAmKcAz heads up I edited the gitignore and also removed some imports and hardcoded things in the test file, check my latest commit if you'd like before I merge this in!

2023-09-07 16:18 UTC, RG-nAmKcAz commented
> @RG-nAmKcAz heads up I edited the gitignore and also removed some imports and hardcoded things in the test file, check my latest commit if you'd like before I merge this in!

You can merge it, but the pipelines fail/hang now without those settings ... oh well

2023-09-07 16:24 UTC, RG-nAmKcAz commented
> > @RG-nAmKcAz heads up I edited the gitignore and also removed some imports and hardcoded things in the test file, check my latest commit if you'd like before I merge this in!
> 
> You can merge it, but the pipelines fail/hang now without those settings ... oh well

Nevermind.. the failure was a github infrastructure failure, not ours

2023-09-07 16:27 UTC, merged